### ISSUE TITLE
Current Fontbakery fail list

### ISSUE THREAD

**Issue by d-sargent** [d-sargent/platypi#3]
Just noting Fontbakery fails I can't work out how to fix yet:

## PPEM must be an integer on hinted fonts.

Issue: Way beyond my understanding. Glyphs Forum has a solution but needs knowledge of 'bash' scripts? I might just remove hinting in Glyphs.

Fix: Run gftool script detailed below. This is a bit advanced for me.

## Check font names are correct

Issue: This affects only affects RIBBI styles. Glyphs seems to be adding in `Typographic Family Name` and `Typographic Subfamily Name` values by default, which Font Bakery doesn't like.

Fix: Unknown.

## ~~Check the OS/2 usWeightClass is appropriate for the font's best SubFamily name.~~

Issue: ~~Only affects Semi Bold and Extra Bold weights? Fontbakery seems to be checking for the wrong usWeightClass of 700 for both (not 800 and 600). Unsure how to fix.~~

Fix: _Now fixed_

## ~~Check glyphs do not have components which are themselves components.~~

Issue: ~~Fontbakery has provided a list of characters affected, so I'll have to go through and examine.~~

Fix: _Now fixed_

**Comment by d-sargent** [comment]
Also adding: current repository setup is not automatically generating font files. It does seem to also be running Fontbakery reports, but not saving these either. Not sure how to fix yet.

**Comment by kenmcd** [comment]
> Check the OS/2 usWeightClass is appropriate for the font's best SubFamily name.

This could be because FB is confused by the names.
And therefore explanation of the issue makes no sense.
`Semi Bold` should always be `SemiBold` (no space).
`Extra Bold` should always be `ExtraBold` (no space).
So if you fix those in Glyphs everywhere they appear this issue may go away.

> Check font names are correct

There are some name issues with the static Italic font.
Typographic Style currently is
`Regular Italic`
and should be
`Italic`
Style Group currently is
`Platypi Regular`
and should be
`Platypi`
Right now that font is alone in its own `Platypi Regular` style group, 
when it should be in the `Platypi` RIBBI style group.

This issue and the names above will probably make this go away.

TransType is very useful to check name issues.
And makes it easy to visualize.

**Before** (current state)
![Names-1-before](https://github.com/d-sargent/platypi/assets/844920/683d9498-27ea-43ac-8e07-5dc4882df6ce)

**After** (after the fixes described above)
![Names-2-after](https://github.com/d-sargent/platypi/assets/844920/11015c29-e1dc-47c5-8a68-bef9e2867f63)

These are issues you will need to fix in Glyphs.

Note: GF is probably going to ask you to add Medium (500).
Their build process for their online versions will add Medium (500).
So you should probably just add it now.

**Comment by kenmcd** [comment]
> Check glyphs do not have components which are themselves components.

Also called nested components.
For example in Platypi now
`/acircumflexgrave`
is made of two components
`/a` and 
`/circumflexcomb_gravecomb`
and that component is made of two other components
`/circumflexcomb` and `/gravecomb`
So you have components made of components (nested components).

Some printer drivers and applications cannot handle this and the components end up in the wrong places (left or right, or on the baseline, etc.).
So one solution would be to decompose the `/circumflexcomb_gravecomb` breaking the links to its components.

**Comment by kenmcd** [comment]
> PPEM must be an integer on hinted fonts.

https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/integer_ppem_if_hinted
I think there is a utility in `gftools` which can set this bit and "fix" the fonts.
This can be added to the font building script to happen automatically.
For now you may just want to ignore this one until the GF folks get here.
(because there is no easy way to do this in Glyphs AFAIK)

**gftools** is here:
https://github.com/googlefonts/gftools

**Comment by d-sargent** [comment]
🙌 thanks again @kenmcd this is all _very_ helpful.

**Comment by kenmcd** [comment]
Fix for the hinting - run manually.

To run the script do: `gftools fix-hinting font.ttf`

**Comment by d-sargent** [comment]
> This could be because FB is confused by the names.
> And therefore explanation of the issue makes no sense.
> `Semi Bold` should always be `SemiBold` (no space).
> `Extra Bold` should always be `ExtraBold` (no space).
> So if you fix those in Glyphs everywhere they appear this issue may go away.

Thanks @kenmcd this fixed the _OS/2 usWeightClass_ fail! I've been banging my head on the desk about this one, and it was such a simple fix. 

The _Check font names are correct_ fail is still occurring, but now only on the four RIBBI styles. Glyphs seems to be adding in `Typographic Family Name` and `Typographic Subfamily Name` values by default, which Font Bakery doesn't like. All the other settings are correct according to the GF style linking page, so perhaps there is a Glyphs setting I don't know about.

Also added a Medium weight, thanks for the tip.

**Comment by kenmcd** [comment]
Looks good now...
![Build#146](https://github.com/d-sargent/platypi/assets/844920/c148c702-0c82-4e6d-b088-8f41930fe6c7)

Per Glyphs docs they do not include Name ID 16+17 if they match Name ID 1+2.
And I checked the RIBBI fonts in OTMaster - there are no Name ID 16 or 17 in those four fonts.

So I will take a look at the latest FB report and see what it is saying...

**Comment by kenmcd** [comment]
I ran FontBakery version `0.10.9` locally on the latest TTF files and did not get any naming issues reported.
The version of FontBakery in the report with the fonts is `0.8.13`.
Updating FontBakery would be a good idea.

**Comment by d-sargent** [comment]
Thanks @kenmcd looks like I need to learn how to drive the repository using command lines then! 🤓

**Comment by d-sargent** [comment]
Thanks @kenmcd I've fixed the nested component fail now. I decomposed the troublemakers as advised.

I bumbled around with the Terminal and managed to update the Repository Template. This seems to have broken the little report badges along the top of the `README.md` file... which I will take as a sign I should not be meddling with any more code witchcraft! 

I'm satisfied I've been able to develop this project as far as I can with my level of coding ability. Hopefully, someone at GF can take over and apply these tweaks if it moves forward. Looking at other Repositories this seems common practice.

Thanks again for your time and help; it is truly appreciated.  🙌
