### ISSUE TITLE
Current Repository issues

### ISSUE THREAD

**Issue by d-sargent** [d-sargent/platypi#4]
Current issues with the repository setup I have yet to solve

## Building and saving font files

The current repository setup is not automatically saving font files into a fonts folder like it should be.

## Saving Fontbakery reports on github.io

I think it is generating font files to run Fontbakery reports (as I get the badges with percentages on the home page), but it is not saving these reports in the github.io space where it should be. 

## Wacky Fontbakery badges

These sometimes work, sometimes some of them work, sometimes none of them work. 
 
Not sure how to fix these issues.

**Comment by simoncozens** [comment]
> The current repository setup is not automatically saving font files into a fonts folder like it should be.

At GF we moved away from putting binaries into the repository automatically; the idea is that released versions would be uploaded to a GitHub release, and development versions are available through GitHub Actions artefacts.

> I think it is generating font files to run Fontbakery reports (as I get the badges with percentages on the home page), but it is not saving these reports in the github.io space where it should be.

Grr, we're seeing this in a lot of repos, and I think it's because GitHub changed some default settings. Please ensure that in your "Pages" settings, the "source" is set to "Deploy from a branch" and the "Branch" is set to "gh-pages" and directory to "/ (root)".

I think the badges problem is the same issue.

**Comment by d-sargent** [comment]
> At GF we moved away from putting binaries into the repository automatically; the idea is that released versions would be uploaded to a GitHub release, and development versions are available through GitHub Actions artefacts.

😅 Thanks for that verification!

**Comment by d-sargent** [comment]
> Grr, we're seeing this in a lot of repos, and I think it's because GitHub changed some default settings. Please ensure that in your "Pages" settings, the "source" is set to "Deploy from a branch" and the "Branch" is set to "gh-pages" and directory to "/ (root)".

This fixed the issue, thanks @simoncozens !

**Comment by d-sargent** [comment]
Closing!
